Expose bug #16485 in doctest.
At the moment this bug causes an exception from
sage/rings/polynomial/multi_polynomial_libsingular.pyx:
TypeError: keys do not match self's parent