Patch issue involving locale.
On Dec 23, 2007 11:13 AM, Robert Miller <rlmillster@gmail.com> wrote:
>
> Actually, I don't know if matplotlib has anything to do with this
> issue, as:
>
> File "matrix2.pyx", line 2280, in
> sage.matrix.matrix2.Matrix.echelon_form
>     RuntimeError
>
> ImportError: No module named _locale


Just to be clear -- this problem is not some general Darwin problem.  It doesn't
happen on my ppc Darwin machine ( test-fermat.math.harvard.edu-Darwin.txt)
or on my intel 10.4 Dawin machine (test-leibniz.math.harvard.edu-Darwin.txt).
It also does not happen on my intel 10.5.1 Darwin laptop.  So it's probably
something related to how bsd.math.washington.edu is setup.   That said,
looking at the code in

   /Users/was/build/sage-2.9.1.rc2/local/lib/python2.5/locale.py

it looks really stupid, in that it should have a default fallback behavior,
but is just crashing on some systems (i.e., bsd.math.washington.edu).    And given
that there is _other_ code in locale.py that looks like this:

try:
    from _locale import *
except ImportError:
    # Locale emulation

I suspect we may be hitting a Python bug, which we should report
to Python.

I've written a simple workaround, and made a new version of the python spkg
which patches locale.py appropriately, and placed the new spkg here.

Also, here is the diff:

bash-3.2$ diff Lib/locale.py ../patches/locale.py
28a29
>     EMULATE = False
32a34
>     EMULATE = True
488c490
< if sys.platform in ('win32', 'darwin', 'mac'):
---
> if not EMULATE and sys.platform in ('win32', 'darwin', 'mac'):